# Latent Dirichlet Allocation (LDA)

🎯 The goal of this challenge is to find topics within a corpus of emails with the **LDA** algorithm (Unsupervised Learning in NLP)

✉️ Here is a collection of 1K+ ***unlabelled emails***. Let's try to ***extract topics*** from them!

In [1]:
import pandas as pd

url = 'https://wagon-public-datasets.s3.amazonaws.com/05-Machine-Learning/10-Natural-Language-Processing/lda_data'

data = pd.read_csv(url, sep=",", header=None)
data.columns = ['text']
data.head()

text
0  From: gld@cunixb.cc.columbia.edu (Gary L Dare)...
1  From: atterlep@vela.acs.oakland.edu (Cardinal ...
2  From: miner@kuhub.cc.ukans.edu\nSubject: Re: A...
3  From: atterlep@vela.acs.oakland.edu (Cardinal ...
4  From: vzhivov@superior.carleton.ca (Vladimir Z...

In [2]:
data.shape

(1199, 1)

In [4]:
data.text[0]

'From: gld@cunixb.cc.columbia.edu (Gary L Dare)\nSubject: Stan Fischler, 4/4\nSummary: From the Devils pregame show, prior to hosting the Penguins\nNntp-Posting-Host: cunixb.cc.columbia.edu\nReply-To: gld@cunixb.cc.columbia.edu (Gary L Dare)\nOrganization: PhDs In The Hall\nLines: 32\n\n\nAt the Lester Patrick Awards lunch, Bill Torrey mentioned that one of his\noptions next season is to be president of the Miami team, with Bob Clarke\nworking for him.  At the same dinner, Clarke said that his worst mistake\nin Philadelphia was letting Mike Keenan go -- in retrospect, almost all\nplayers came realize that Keenan knew what it took to win.  Rumours are\nnow circulating that Keenan will be back with the Flyers.\n\nNick Polano is sick of being a scapegoat for the schedule made for the\nRed Wings; After all, Bryan Murray approved it.\n\nGerry Meehan and John Muckler are worried over the Sabres\' prospects;\nAssistant Don Lever says that the Sabres have to get their share now,\nbecause a Que

## (1) Preprocessing 

❓ **Question (Cleaning**) ❓ You're used to it by now... Clean up! Store the cleaned text in a new column "clean_text" of the DataFrame.

In [5]:
import string
from nltk.corpus import stopwords 
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))

def preprocessing(sentence):
    sentence = sentence.strip()
    sentence = sentence.lower()
    sentence = ''.join(char for char in sentence if not char.isdigit())

    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, '')

    tokens = word_tokenize(sentence)
    tokens_cleaned = [w for w in tokens if w not in stop_words]
    lem = [WordNetLemmatizer().lemmatize(w) for w in tokens_cleaned]
    
    cleaned = ' '.join(w for w in lem)
    
    return cleaned

data['clean_text'] = data.text.apply(preprocessing)
data.head()

text  \
0  From: gld@cunixb.cc.columbia.edu (Gary L Dare)...   
1  From: atterlep@vela.acs.oakland.edu (Cardinal ...   
2  From: miner@kuhub.cc.ukans.edu\nSubject: Re: A...   
3  From: atterlep@vela.acs.oakland.edu (Cardinal ...   
4  From: vzhivov@superior.carleton.ca (Vladimir Z...   

                                          clean_text  
0  gldcunixbcccolumbiaedu gary l dare subject sta...  
1  atterlepvelaacsoaklandedu cardinal ximenez sub...  
2  minerkuhubccukansedu subject ancient book orga...  
3  atterlepvelaacsoaklandedu cardinal ximenez sub...  
4  vzhivovsuperiorcarletonca vladimir zhivov subj...

## (2) Latent Dirichlet Allocation model

❓ **Question (Training)** ❓ Train a LDA model to extract potential topics

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

vectorized = vectorizer.fit_transform(data.clean_text)
vectorized = pd.DataFrame(vectorized.toarray(), columns=vectorizer.get_feature_names_out())
vectorized

aa  \
0     0.0   
1     0.0   
2     0.0   
3     0.0   
4     0.0   
...   ...   
1194  0.0   
1195  0.0   
1196  0.0   
1197  0.0   
1198  0.0   

      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaauuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuugggggggggggggggg  \
0                                                   0.0                                 
1                                                   0.0                                 
2                                                   0.0                                 
3                                                   0.0                                 
4                                                   0.0                                 
...                                                 ...                                 
1194                                                0.0                                 
1195                                                0.0                                 
1196                                                0.0                                 
1197                                                0.0                                 
1198                                                0.0                                 

      aacc  aadams  aafreenetcarletonca  aargh  aaron  \
0      0.0     0.0             0.000000    0.0    0.0   
1      0.0     0.0             0.086861    0.0    0.0   
2      0.0     0.0             0.000000    0.0    0.0   
3      0.0     0.0             0.000000    0.0    0.0   
4      0.0     0.0             0.000000    0.0    0.0   
...    ...     ...                  ...    ...    ...   
1194   0.0     0.0             0.000000    0.0    0.0   
1195   0.0     0.0             0.000000    0.0    0.0   
1196   0.0     0.0             0.000000    0.0    0.0   
1197   0.0     0.0             0.000000    0.0    0.0   
1198   0.0     0.0             0.000000    0.0    0.0   

      aaronbinahccbrandeisedu  aaroncathenamitedu  aassists  ...  zombo  \
0                         0.0                 0.0       0.0  ...    0.0   
1                         0.0                 0.0       0.0  ...    0.0   
2                         0.0                 0.0       0.0  ...    0.0   
3                         0.0                 0.0       0.0  ...    0.0   
4                         0.0                 0.0       0.0  ...    0.0   
...                       ...                 ...       ...  ...    ...   
1194                      0.0                 0.0       0.0  ...    0.0   
1195                      0.0                 0.0       0.0  ...    0.0   
1196                      0.0                 0.0       0.0  ...    0.0   
1197                      0.0                 0.0       0.0  ...    0.0   
1198                      0.0                 0.0       0.0  ...    0.0   

          zone  zoo  zoomed  zorasterism  zubov  zupancic  zurich  zwart  \
0     0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
1     0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
2     0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
3     0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
4     0.071741  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
...        ...  ...     ...          ...    ...       ...     ...    ...   
1194  0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
1195  0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
1196  0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
1197  0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   
1198  0.000000  0.0     0.0          0.0    0.0       0.0     0.0    0.0   

      zzzzzz  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
...      ...  
1194     0.0  
1195     0.0  
1196     0.0  
1197     0.0  
1198     0.0  

[1199 rows x 19389 columns]

In [7]:
from sklearn.decomposition import LatentDirichletAllocation

# Instantiate the LDA
n_components = 2
lda_model = LatentDirichletAllocation(n_components=n_components, max_iter = 100)

# Fit the LDA on the vectorized documents
lda_model.fit(vectorized)

LatentDirichletAllocation(max_iter=100, n_components=2)

##  (3) Visualize potential topics

🎁 We coded for you a  function that prints the words associated with the potential topics.

In [10]:
lda_model.components_

array([[0.875122  , 0.50498853, 0.53398308, ..., 0.50297036, 0.83402124,
        0.50331859],
       [0.52556632, 0.59606549, 0.50061056, ..., 0.65602352, 0.50478785,
        0.67861733]])

In [15]:
lda_model.components_.shape

(2, 19389)

In [13]:
lda_model.components_[0].argsort()

array([ 7907, 14773,   974, ...,  9028,  2882,  7156])

In [16]:
lda_model.components_[0][7156]

35.547221074759705

In [8]:
def print_topics(model, vectorizer):
    for idx, topic in enumerate(model.components_):
        print("Topic %d:" % (idx))
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                        for i in topic.argsort()[:-10 - 1:-1]])

❓ **Question** ❓ Print the topics extracted by your LDA.

In [9]:
print_topics(lda_model, vectorizer)

Topic 0:
[('god', 35.547221074759705), ('christian', 22.323243140689655), ('jesus', 18.979069934494134), ('people', 17.347423215064367), ('would', 16.54408149784087), ('church', 16.436279962763027), ('one', 16.348973803532196), ('bible', 13.696513910295815), ('believe', 13.576398428849581), ('say', 12.986088182281094)]
Topic 1:
[('game', 26.682214421074317), ('team', 25.45499623193334), ('hockey', 18.505372556426988), ('player', 18.165473346127996), ('go', 15.277294536215713), ('play', 14.489767414872713), ('nhl', 13.45572818692019), ('year', 13.286824975231788), ('university', 13.15115325128095), ('playoff', 13.088656468497245)]


## (4) Predict the document-topic mixture of a new text

❓ **Question (Prediction)** ❓

Now that your LDA model is fitted, you can use it to predict the topics of a new text.

1. Vectorize the example
2. Use the LDA on the vectorized example to predict the topics

In [18]:
example = ["My team performed poorly last season. Their best player was out injured and only played one game"]

In [30]:
import numpy as np

clean_ex = [preprocessing(example[0])]

clean_ex = vectorizer.fit_transform(clean_ex)
clean_ex = pd.DataFrame(
    clean_ex.toarray(),
    columns = vectorizer.get_feature_names_out()
)
clean_ex

best      game   injured      last       one  performed    played  \
0  0.301511  0.301511  0.301511  0.301511  0.301511   0.301511  0.301511   

     player    poorly    season      team  
0  0.301511  0.301511  0.301511  0.301511

In [32]:
prediction = lda_model.fit_transform(clean_ex)
prediction

array([[0.15752267, 0.84247733]])

🏁 Congratulations! You know how to implement an LDA quickly.

💾 Don't forget to `git add/commit/push` your notebook...

🚀 ... and move on to the next challenge!